sudo: required

services:
 - docker

env:
  global:
    - OMP_NUM_THREADS=2
  matrix:
    - IMG=ubuntu:18.04
    - IMG=ubuntu:19.04
    - IMG=ubuntu:19.10
    - IMG=ubuntu:20.04
    - IMG=debian:unstable
    - IMG=debian:testing

script:
  - docker build --build-arg "OMP_NUM_THREADS=${OMP_NUM_THREADS}" --build-arg "${IMG}" "."
