language: python
os: linux
dist: xenial
python: 3.7

services:
 - docker

stages:
    - test
    - post
env:
  global:
    - OMP_NUM_THREADS=2
  jobs:
    - IMG=debian:bookworm

jobs:
  allow_failures:
    - env: IMG=debian:bullseye
  include:
    - env: IMG=""
      stage: post
      dist: bionic
      python: 3.8
      script:
      -  true

script:
  - docker build --build-arg "OMP_NUM_THREADS=${OMP_NUM_THREADS}" --build-arg "IMG=${IMG}" "."
